/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole.StudentRoleWorkResp02;

import Business.Business;
import Business.Course.Course;
import Business.Profiles.FacultyDirectory;
import Business.Profiles.FacultyProfile;
import Business.Profiles.StudentProfile;
import UserInterface.WorkAreas.StudentRole.StudentWorkAreaJPanel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sujata
 */
public class CourseRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CourseRegistrationJPanel
     */
    javax.swing.JPanel CardSequencePanel;
    Business business;
    StudentProfile student;

    public CourseRegistrationJPanel(Business business, StudentProfile student, JPanel cp) {
        initComponents();
        this.business = business;
        this.student = student;
        this.CardSequencePanel = cp;
        populateCourseTable();
    }
    
     private void populateCourseTable() {
        DefaultTableModel model = (DefaultTableModel) tblListMyCourses.getModel();
        model.setRowCount(0);

        for(Course course : student.getRegisteredCourseList()) {
            Object[] row = new Object[7];
            row[0] = course;
            row[1] = course.getCourseID();
            row[2] = course.getFacultyProfile().getPerson().getName();
            row[3] = course.getTermOfferedIn();
            row[4] = course.getLanguage();
            row[5] = course.getRegion();
            row[6] = course.getTermOfferedIn();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCourseRegistration = new javax.swing.JLabel();
        lblCourseID = new javax.swing.JLabel();
        txtCR_CourseID = new javax.swing.JTextField();
        btnCR_RegisterCourse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListMyCourses = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        lblCourseRegistration.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lblCourseRegistration.setForeground(new java.awt.Color(255, 255, 255));
        lblCourseRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCourseRegistration.setText("Course Registration");

        lblCourseID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCourseID.setForeground(new java.awt.Color(255, 255, 255));
        lblCourseID.setText("Course ID:");

        txtCR_CourseID.setBackground(new java.awt.Color(204, 204, 204));
        txtCR_CourseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCR_CourseIDActionPerformed(evt);
            }
        });

        btnCR_RegisterCourse.setBackground(new java.awt.Color(0, 153, 255));
        btnCR_RegisterCourse.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCR_RegisterCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnCR_RegisterCourse.setText("Register!!!");
        btnCR_RegisterCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCR_RegisterCourseActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter the Course ID to register for a new course");

        tblListMyCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Course Name", "Course ID", "Instructor", "Semester", "Language", "Region", "Term Offered In"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListMyCourses);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("My registered courses");

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(lblCourseID)
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCR_RegisterCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(txtCR_CourseID)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(250, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214)
                        .addComponent(lblCourseRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(jLabel1)))
                .addGap(0, 430, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblCourseRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCR_CourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseID))
                .addGap(18, 18, 18)
                .addComponent(btnCR_RegisterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCR_RegisterCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCR_RegisterCourseActionPerformed
//        // TODO add your handling code here:
        Course result = business.getCourseDirectory().searchCourse(txtCR_CourseID.getText());
        if(result == null){
            JOptionPane.showMessageDialog(null, "Course Not Found.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            student.enrollToCourse(result);
            FacultyProfile facultyProfile = result.getFacultyProfile();
            FacultyDirectory facultyDir = business.getFacultydirectory();
            
            FacultyProfile facultyProfileRef = facultyDir.findFaculty(facultyProfile.getPerson().getId());
            facultyProfileRef.addStudentToClass(student);
            JOptionPane.showMessageDialog(null, "Registered To the Course", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtCR_CourseID.setText("");
            populateCourseTable();
        }
    }//GEN-LAST:event_btnCR_RegisterCourseActionPerformed

    private void txtCR_CourseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCR_CourseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCR_CourseIDActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel); //navigates back to previous page
        //        CardSequencePanel.add("StudentWorkArea", StudentWorkAreaJPanel);
        // layout.previous(CardSequencePanel);

        StudentWorkAreaJPanel studentWorkAreaPanel = new StudentWorkAreaJPanel(business, student, CardSequencePanel);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("studentWorkArea", studentWorkAreaPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCR_RegisterCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourseID;
    private javax.swing.JLabel lblCourseRegistration;
    private javax.swing.JTable tblListMyCourses;
    private javax.swing.JTextField txtCR_CourseID;
    // End of variables declaration//GEN-END:variables
}
