/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole.StudentRoleWorkResp04;




import Business.Business;
import Business.Profiles.StudentProfile;
import UserInterface.WorkAreas.StudentRole.StudentWorkAreaJPanel;
import javax.swing.JPanel;


/**
 *
 * @author sakshiwadaskar
 */
public class GraduationAuditJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GraduationAuditJPanel
     */
    javax.swing.JPanel CardSequencePanel;
    Business business;
    StudentProfile student;
    public GraduationAuditJPanel(Business b, StudentProfile spp, JPanel clp) {
        initComponents();
        business = b;
        this.CardSequencePanel = clp;
        student = spp;
        
        controlUIElements();
    }
    
    private void controlUIElements() {
        if (student.isGraduated()) {
            lblCongrats.setVisible(true);
            lblDegree.setVisible(true);
            lblStudentName.setVisible(true);
            lblStudentName.setText(student.getPerson().getName());
            btnApplyToGraduate.setVisible(false);
        } else {
            lblCongrats.setVisible(false);
            lblDegree.setVisible(false);
            btnApplyToGraduate.setVisible(true);
            lblStudentName.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnApplyToGraduate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblCongrats = new javax.swing.JLabel();
        lblDegree = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        btnApplyToGraduate.setBackground(new java.awt.Color(0, 153, 255));
        btnApplyToGraduate.setForeground(new java.awt.Color(255, 255, 255));
        btnApplyToGraduate.setText("Apply for Graduation!");
        btnApplyToGraduate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyToGraduateActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCongrats.setFont(new java.awt.Font("Charm", 1, 24)); // NOI18N
        lblCongrats.setText("Congratulations! You have graduated with the degree:");

        lblDegree.setFont(new java.awt.Font("Charm", 1, 24)); // NOI18N
        lblDegree.setText("MS in Information Systems");

        lblStudentName.setFont(new java.awt.Font("Charmonman", 1, 24)); // NOI18N
        lblStudentName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStudentName.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(lblDegree))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(451, 451, 451)
                        .addComponent(btnApplyToGraduate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCongrats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStudentName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnBack)
                .addGap(133, 133, 133)
                .addComponent(lblStudentName)
                .addGap(18, 18, 18)
                .addComponent(lblCongrats)
                .addGap(18, 18, 18)
                .addComponent(lblDegree)
                .addGap(82, 82, 82)
                .addComponent(btnApplyToGraduate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyToGraduateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyToGraduateActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnApplyToGraduateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel); //navigates back to previous page

        StudentWorkAreaJPanel studentWorkAreaPanel = new StudentWorkAreaJPanel(business, student, CardSequencePanel);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("studentWorkArea", studentWorkAreaPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyToGraduate;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblCongrats;
    private javax.swing.JLabel lblDegree;
    private javax.swing.JLabel lblStudentName;
    // End of variables declaration//GEN-END:variables
}
