/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import Business.Profiles.EmployeeProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import UserInterface.WorkAreas.AdminRole.AdminRoleWorkAreaJPanel;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kal bugrara
 */
public class ManageUserAccountsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    UserAccount selecteduseraccount;
    EmployeeProfile employeeProfile;

    public ManageUserAccountsJPanel(Business bz, EmployeeProfile ep, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        this.employeeProfile = ep;
        initComponents();
        refreshTable();

    }

    public void refreshTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblUserAcc.getModel();
        dtm.setRowCount(0);
        UserAccountDirectory uad = business.getUserAccountDirectory();
        for (UserAccount userAcc : uad.getUserAccountList()) {
            String userName = userAcc.getUserLoginName();
            String fullName = userAcc.getUserProfile().getPerson().getName();
            String role = userAcc.getRole();
            String phNum = userAcc.getUserProfile().getPerson().getPhoneNumber();

            Object[] row = new Object[4];
            row[0] = userName;
            row[1] = fullName;
            row[2] = role;
            row[3] = phNum;
            dtm.addRow(row);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserAcc = new javax.swing.JTable();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(null);

        Back.setBackground(new java.awt.Color(0, 153, 255));
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(30, 300, 80, 23);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Accounts");
        add(jLabel1);
        jLabel1.setBounds(30, 90, 190, 17);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("View User Accounts");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        tblUserAcc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User Name", "Full Name", "Role", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblUserAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblUserAccMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblUserAcc);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 110, 550, 130);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.removeAll();
        AdminRoleWorkAreaJPanel adminWorkAreaPanel = new AdminRoleWorkAreaJPanel(business, employeeProfile, CardSequencePanel);
        CardSequencePanel.add("adminWorkAreaPanel", adminWorkAreaPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_BackActionPerformed

    private void tblUserAccMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserAccMousePressed
        // Extracts the row (uaser account) in the table that is selected by the user
        


    }//GEN-LAST:event_tblUserAccMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUserAcc;
    // End of variables declaration//GEN-END:variables

}
